#!/bin/bash
# to be added as a pre-commit hook - compiles to-do items from repo
# it is dumb, so won't ignore any gitignored files - don't litter them, or expect noise!
grep TODO -r . > todo_list
git add todo_list
echo "You have probably misspelled calypso some places - a likely source of errors!" > warnings
grep calyspo -r . > warnings
