#!/bin/bash
# to be added as a pre-commit hook - compiles to-do items from repo
# it is dumb, so won't ignore any gitignored files - don't litter them, or expect noise!
grep TODO --exclude={pre-commit,calypso.css} --exclude-dir={.git,misc} -n -r . > misc/todo_list
git add misc/todo_list
echo "You have probably misspelled calypso some places - a likely source of errors!" > misc/warnings
grep calyspo --exclude="pre-commit" --exclude-dir={.git,misc} -n -r . >> misc/warnings
git add misc/warnings
